server:
  port : 1245

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/MyApp?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: mauFJcuf5dhRMQrjj
    driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher